package latina.vista;

public enum Eventos {
    REGISTRAR_ROL,
    ASIGNAR_TURNO,
    DESASIGNAR_TURNO,
    OBTENER_TURNOS_POR_DIA,
    OBTENER_TURNOS_ASIGNADOS_POR_DIA,
    OBTENER_EMPLEADOS_DISPONIBLES,
    REGISTRAR_EMPLEADO,
    OBTENER_TODOS_LOS_EMPLEADOS,
    REGISTRAR_DISPONIBILIDAD,
    OBTENER_TODOS_LOS_ROLES,
    REGISTRAR_TURNO,
    OBTENER_TURNOS_SEMANALES,
    REGISTRAR_FICHAJE,
    INICIAR_SESION,
    ACTUALIZAR_ESTADO_FICHAJE,
    OBTENER_ESTADO_FICHAJE,
    BUSCAR_TURNO_A_FICHAR,
    INICIALIZAR_GERENTE
}
